services:
    database:
        container_name: talent_hub_database
        image: postgres:12
        environment:
            POSTGRES_USER: ${DB_USER:-root}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-talentHubPassword123}
            POSTGRES_DB: ${DB_NAME:-talentHub}
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-talentHubRootPassword123}
            PGLOG: 'csvlog'
            LOGGING_LEVEL: 'debug'
        ports:
            - '${DB_PORT:-5432}:5432'
        volumes:
            - database_data:/var/lib/postgresql/data
        env_file:
            - ../../.env
        restart: unless-stopped
        command: >
            postgres
            -c log_statement=all
            -c logging_collector=on
            -c log_destination=stderr
            -c log_directory='/var/log/postgresql'
            -c log_filename='postgresql.log'
            -c log_rotation_age=0
            -c log_min_messages=DEBUG5
            -c log_connections=on
            -c log_disconnections=on
            -c log_duration=on
            -c log_lock_waits=on
            -c log_temp_files=0
            -c log_timezone='UTC'

    cache:
        container_name: talent_hub_cache
        image: redis:latest
        ports:
            - '${CACHE_PORT:-1293}:6379'
        env_file:
            - ../../.env
        restart: unless-stopped

volumes:
    database_data:
