version: '3.7'

services:
  database:
    container_name: talent_hub_database
    image: postgres:12
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - database_data:/var/lib/postgresql/data
    env_file:
      - .env

  cache:
    container_name: talent_hub_cache
    image: redis:latest
    ports:
      - '${CACHE_PORT}:6379'

volumes:
  database_data:
